### YamlMime:Role 
title: 데이터 엔지니어  
metadata: 
  title: 데이터 엔지니어 
  description: 데이터 엔지니어는 데이터 서비스의 전체 스택을 사용하여 데이터 괸리, 모니터링, 보안과 개인 정보 보호 기능을 설계하고 구현합니다.
uid: role.data-engineer 
summary: | 
  데이터 엔지니어는 데이터 서비스의 전체 스택을 사용하여 데이터 괸리, 모니터링, 보안과 개인 정보 보호 기능을 설계하고 구현합니다.
subTitle: 데이터 엔지니어는 데이터 서비스의 전체 스택을 사용하여 데이터 괸리, 모니터링, 보안과 개인 정보 보호 기능을 설계하고 구현합니다.
certificationPaths: 
- title: Azure Data Engineer
  linkedInKeywords: Azure Data Engineer
  uid: certification-path.azure-data-engineer 
  prerequisites: 
  - uid: certification.azure-fundamentals
    isOptional: true
    levels:
    - beginner 
  - uid: certification.azure-data-engineer
    levels:
    - intermediate  
certifications:
- uid: certification.azure-data-engineer
  requiredExams:
  - uid: exam.dp-200
  - uid: exam.dp-201
resources:
- title: Microsoft 교육 및 인증 가이드
  description: 간략 교육 및 인증 가이드에서 모든 인증을 설명합니다.
  href: https://query.prod.cms.rt.microsoft.com/cms/api/am/binary/RWtQJJ
- title: 교육 및 인증 포스터
  description: 이 교육 및 인증 포스터를 통해 성공을 위한 길을 선택합니다.
  href: https://query.prod.cms.rt.microsoft.com/cms/api/am/binary/RE2PjDI
- title: 인증 지원
  href: ../help.md
  description: Microsoft 인증 지원 포럼에서 도움을 받으십시오. 포럼 조정자는 월요일에서 금요일까지 업무일 하루만에 응답할 것입니다.
